// COLLECT HERE ALL ACTION TYPES //

// AUTHENTICATION ACTIONS
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const UPD_BOX_FLAG = 'UPD_BOX_FLAG';
export const UPD_USER_DATA = 'UPD_USER_DATA';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

// ACCOUNT ACTIONS
export const KARMA_CHANGE = 'KARMA_CHANGE';
export const BALANCE_UPD = 'BALANCE_UPD';

// NAVIGATION ACTIONS
export const SCREEN_PUSH = 'SCREEN_PUSH';
export const SCREEN_POP = 'SCREEN_POP';
export const SCREEN_POP_PUSH = 'SCREEN_POP_PUSH';
export const CHANGE_APP_SECTION = 'CHANGE_APP_SECTION';

// DATA MANAGEMENT RELATED ACTIONS
export const BACK_UP_TRX = 'BACK_UP_TRX';
export const UPDATE_PENDING_TRXS = 'UPDATE_PENDING_TRXS';
export const REMOVE_PENDING_TRX = 'REMOVE_PENDING_TRX';

export const FETCH_FEED = 'FETCH_FEED';
export const FETCH_FEED_SUCCESS = 'FETCH_FEED_SUCCESS';
export const FETCH_FEED_TIMEOUT = 'FETCH_FEED_TIMEOUT';
export const FETCH_FEED_FAIL = 'FETCH_FEED_FAIL';

export const FETCH_SURVEY = 'FETCH_SURVEY';
export const FETCH_SURVEY_SUCCESS = 'FETCH_SURVEY_SUCCESS';
export const FETCH_SURVEY_TIMEOUT = 'FETCH_SURVEY_TIMEOUT';
export const FETCH_SURVEY_FAIL = 'FETCH_SURVEY_FAIL';

export const FETCH_USERDATA = 'FETCH_USERDATA';
export const FETCH_USERDATA_SUCCESS = 'FETCH_USERDATA_SUCCESS';
export const FETCH_USERDATA_TIMEOUT = 'FETCH_USERDATA_TIMEOUT';
export const FETCH_USERDATA_FAIL = 'FETCH_USERDATA_FAIL';

export const ADD_SURVEY = 'ADD_SURVEY';
export const ADD_SURVEY_SUCCESS = 'ADD_SURVEY_SUCCESS';
export const ADD_SURVEY_TIMEOUT = 'ADD_SURVEY_TIMEOUT';
export const ADD_SURVEY_FAIL = 'ADD_SURVEY_FAIL';

export const VOTE_SURVEY = 'VOTE_SURVEY';
export const VOTE_SURVEY_SUCCESS = 'VOTE_SURVEY_SUCCESS';
export const VOTE_SURVEY_TIMEOUT = 'VOTE_SURVEY_TIMEOUT';
export const VOTE_SURVEY_FAIL = 'VOTE_SURVEY_FAIL';
